### ISSUE TITLE
如何包装一个Markdown编辑器？

### ISSUE THREAD

**Issue by panxiaoguang** [jiangmiemie/PyneconeBlog#1]
我也有类似的应用，不过我不懂前后端，自己看着文档胡乱写的QAQ，https://github.com/panxiaoguang/myBlog。

我想实现的是用sqlite存储文章信息，文章主要信息当然是markdown. 但是还缺少一个关键问题，如何搞定一个Markdown编辑器来直接写文章并上传的数据库，我尝试找了好多的NPM库，包装都报错。

不知道大佬有没有类似的方法供我参考啊

**Comment by jiangmiemie** [comment]
我喜欢用vscode（代码编辑器），里面安装了一个Micro office插件，这个插件同时也支持markdown预览和编写。

然后我是直接上传的md源数据字符串到数据库。用pynecone自带的pc.markdown语法（内核是react-markdown).对一些自己想要的样式通过css单独定义（如行距、字号、表格样式等等）这部分可以看我在pynecone的Discord中help区的子区 buildful markdown区

**Comment by panxiaoguang** [comment]
> 我喜欢用vscode（代码编辑器），里面安装了一个Micro office插件，这个插件同时也支持markdown预览和编写。
> 
> 然后我是直接上传的md源数据字符串到数据库。用pynecone自带的pc.markdown语法（内核是react-markdown).对一些自己想要的样式通过css单独定义（如行距、字号、表格样式等等）这部分可以看我在pynecone的Discord中help区的子区 buildful markdown区

如上所说，这样做似乎丢弃了pynecone作为全栈的能力，直接写markdown更像是只用前端渲染的typecho之类的工具。

**Comment by jiangmiemie** [comment]
pynecone 成为不了全栈框架的链接者 ， 他只是我们迈往全栈工程师路上的一个玩具。

**Comment by panxiaoguang** [comment]
> pynecone 成为不了全栈框架的链接者 ， 他只是我们迈往全栈工程师路上的一个玩具。

他有另外的意义，例如我作为一个做生物信息学的科研工作者，我只有有限的web知识，但却希望将我们的科研数据或者深度学习预测模型搭建在网页之上。在这里，pynecone不只是一个玩具，它扮演了救……星，相比streamlit 和Dash, 它的通用性更强。但是目前我发现的一个巨大缺陷就是，包装自己的react组件并非易事，当然，这也跟它刚起步，社区并不丰富有关……

**Comment by jiangmiemie** [comment]
这就是问题所在，当你学会了包装自己的react组件，你就已经可以直接使用react本身了。

**Comment by jiangmiemie** [comment]
如果你想做一个类似别人网站博客后台的那种东西，可以试试写两个框

左边的框是 input组件。 右边的框用pc.markdwon 生成预览

两个框通过pc.Var链接

再加一个按钮：确认写入数据库

后面可能还需要：增删改查之类的功能，大同小异了

**Comment by jiangmiemie** [comment]
https://python-markdown.github.io/reference/  不想用react-markdown可以用这个
